RINK_NAMES = {
    38: "Sugar Land Ice & Sports Center Rink B",
    39: "Bellerive Ice Center",
    103: "Aerodrome",
    153: "Valley Ranch Norman Green",
    154: "Valley Ranch Ken Hitchcock",
    191: "Chaparral Ice Center Northcross",
    419: "Plano US Rink",
    420: "Plano World Rink",
    421: "Richardson Blue Rink",
    422: "Richardson Red Rink",
    484: "Farmers Branch Bob Gainey Rink",
    485: "Farmers Branch Tom Gaglardi Rink",
    486: "McKinney North Rink",
    487: "McKinney South Rink",
    762: "Mansfield Derian Hatcher Rink",
    763: "Mansfield Brenden Morrow Rink",
    1178: "Spirit Ice Arena",
    264: "Palm Beach Skate Zone Rink 1",
    265: "Palm Beach Skate Zone Rink 2",
    1226: "Palm Beach Skate Zone Rink 3",
    1271: "Ford Ice Center Antioch North",
    1272: "Ford Ice Center Antioch South",
    1359: "NYTEX Brahmas Rink",
    1360: "NYTEX West Rink",
    1576: "Ice and Field at Crossover Silver Rink",
    1577: "Ice and Field at Crossover Gold Rink",
    3239: "Centennial Sportsplex Nashville Rink A",
    3240: "Centennial Sportsplex Nashville Rink B",
}
